const fs = require('fs');

const data = {
  payment_methods: [
    { id: 1, code: 'GOPAY', name: 'GoPay', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/8/86/Gopay_logo.svg', type: 'E-Wallet', provider: 'Midtrans', is_active: true, sort_order: 1 },
    { id: 2, code: 'BCAVA', name: 'BCA Virtual Account', logo_url: 'https://upload.wikimedia.org/wikipedia/id/e/e0/BCA_logo.svg', type: 'Bank Transfer', provider: 'Xendit', is_active: true, sort_order: 2 },
    { id: 3, code: 'MANDIRIVA', name: 'Mandiri Virtual Account', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Logo_of_Bank_Mandiri.svg', type: 'Bank Transfer', provider: 'Xendit', is_active: true, sort_order: 3 },
    { id: 4, code: 'BSIVA', name: 'BSI Virtual Account', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Bank_Syariah_Indonesia.svg', type: 'Bank Transfer', provider: 'Xendit', is_active: true, sort_order: 4 },
    { id: 5, code: 'MANUAL_BSI', name: 'BSI Manual Transfer', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Bank_Syariah_Indonesia.svg', type: 'Manual Transfer', provider: 'Manual', is_active: true, sort_order: 5 },
    { id: 6, code: 'BRIVA', name: 'BRI Virtual Account', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/9/9e/BRI_2020.svg', type: 'Bank Transfer', provider: 'Xendit', is_active: true, sort_order: 6 },
    { id: 7, code: 'BNIVA', name: 'BNI Virtual Account', logo_url: 'https://upload.wikimedia.org/wikipedia/id/5/55/BNI_logo.svg', type: 'Bank Transfer', provider: 'Xendit', is_active: true, sort_order: 7 },
    { id: 8, code: 'BJBVA', name: 'BJB Virtual Account', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/9/91/Logo_Bank_BJB.svg', type: 'Bank Transfer', provider: 'Xendit', is_active: true, sort_order: 8 },
    { id: 9, code: 'BNCVA', name: 'BNC Virtual Account', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/1/10/Logo_Bank_Neo_Commerce.svg', type: 'Bank Transfer', provider: 'Xendit', is_active: true, sort_order: 9 },
    { id: 10, code: 'CIMBVA', name: 'CIMB Virtual Account', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/b/b8/CIMB_Niaga_logo.svg', type: 'Bank Transfer', provider: 'Xendit', is_active: true, sort_order: 10 },
    { id: 11, code: 'MUAMALATVA', name: 'Muamalat Virtual Account', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/4/41/Logo_Bank_Muamalat.svg', type: 'Bank Transfer', provider: 'Xendit', is_active: true, sort_order: 11 },
    { id: 12, code: 'PERMATAVA', name: 'Permata Virtual Account', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/3/38/PermataBank_logo.svg', type: 'Bank Transfer', provider: 'Xendit', is_active: true, sort_order: 12 },
    { id: 13, code: 'ALFAMART', name: 'Alfamart', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/8/86/Alfamart_logo.svg', type: 'Retail Outlet', provider: 'Xendit', is_active: true, sort_order: 13 },
    { id: 14, code: 'INDOMARET', name: 'Indomaret', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Logo_Indomaret.png', type: 'Retail Outlet', provider: 'Xendit', is_active: true, sort_order: 14 }
  ],
  payment_instructions: [
    { id: 1, payment_method_id: 2, title: 'Pembayaran via m-BCA', content: '<ol><li>Buka aplikasi BCA Mobile dan login.</li><li>Pilih menu <strong>m-Transfer</strong> > <strong>BCA Virtual Account</strong>.</li><li>Masukkan nomor Virtual Account yang tertera di atas dan klik <strong>Send</strong>.</li><li>Masukkan PIN Anda untuk mengotorisasi transaksi.</li></ol>', sort_order: 1 },
    { id: 2, payment_method_id: 2, title: 'Pembayaran via KlikBCA Individual', content: '<ol><li>Login ke KlikBCA Individual.</li><li>Pilih <strong>Transfer</strong>, lalu pilih <strong>Transfer ke BCA Virtual Account</strong>.</li><li>Masukkan nomor Virtual Account.</li><li>Pilih Lanjutkan untuk memproses pembayaran.</li><li>Masukkan RESPON KEYBCA APPLI 1 yang ditunjukkan pada Token BCA Anda, lalu klik tombol Kirim.</li></ol>', sort_order: 2 },
    { id: 3, payment_method_id: 2, title: 'Pembayaran via ATM BCA', content: '<ol><li>Masukkan kartu ATM BCA dan PIN Anda.</li><li>Pilih menu <strong>Transaksi Lainnya</strong>.</li><li>Pilih <strong>Transfer</strong>.</li><li>Pilih <strong>Ke BCA Virtual Account</strong>.</li><li>Masukkan Nomor Virtual Account, lalu tekan Benar.</li><li>Verifikasi detail Virtual Account lalu masukkan jumlah yang akan ditransfer dan pilih Benar untuk mengonfirmasi.</li></ol>', sort_order: 3 },

    { id: 4, payment_method_id: 3, title: 'Pembayaran via Livin’ by Mandiri', content: '<ol><li>Login ke aplikasi Livin’ by Mandiri.</li><li>Pilih <strong>Transfer Rupiah</strong> > <strong>Transfer ke penerima baru</strong>.</li><li>Masukkan nomor Virtual Account.</li><li>Masukkan atau konfirmasi jumlah pembayaran.</li><li>Klik Lanjut.</li><li>Masukkan MPIN.</li></ol>', sort_order: 1 },
    { id: 5, payment_method_id: 3, title: 'Pembayaran via ATM Mandiri', content: '<ol><li>Masukkan Kartu ATM.</li><li>Pilih bahasa yang diinginkan.</li><li>Masukkan PIN ATM.</li><li>Pilih <strong>BAYAR/BELI</strong> > <strong>MULTI PAYMENT</strong>.</li><li>Masukkan kode perusahaan 88608 (XENDIT), lalu tekan BENAR.</li><li>Masukkan nomor Virtual Account, lalu tekan BENAR.</li><li>Masukkan jumlah pembayaran, lalu tekan BENAR.</li><li>Konfirmasi detail pembayaran.</li></ol>', sort_order: 2 },

    { id: 6, payment_method_id: 6, title: 'Pembayaran via BRI Mobile (BRIMO)', content: '<ol><li>Login ke aplikasi BRI Mobile Banking.</li><li>Pilih <strong>Pembayaran</strong> > <strong>Briva</strong>.</li><li>Masukkan nomor Virtual Account.</li><li>Masukkan jumlah pembayaran.</li><li>Masukkan PIN.</li><li>Tekan Kirim.</li></ol>', sort_order: 1 },
    { id: 7, payment_method_id: 6, title: 'Pembayaran via ATM BRI', content: '<ol><li>Masukkan Kartu ATM.</li><li>Pilih bahasa yang diinginkan.</li><li>Masukkan PIN ATM.</li><li>Pilih <strong>Menu Lainnya</strong> > <strong>Pembayaran</strong> > <strong>Pembayaran Lainnya</strong> > <strong>BRIVA</strong>.</li><li>Masukkan nomor Virtual Account.</li><li>Masukkan jumlah pembayaran.</li><li>Konfirmasi detail pembayaran dan tekan YA.</li></ol>', sort_order: 2 },

    { id: 8, payment_method_id: 7, title: 'Pembayaran via BNI Mobile Banking', content: '<ol><li>Login ke aplikasi BNI Mobile Banking.</li><li>Klik <strong>Transfer</strong> > <strong>Virtual Account Billing</strong>, lalu pilih rekening debet.</li><li>Masukkan nomor Virtual Account.</li><li>Jumlah pembayaran akan ditampilkan di layar.</li><li>Konfirmasi informasi pembayaran.</li><li>Masukkan password transaksi.</li></ol>', sort_order: 1 },
    { id: 9, payment_method_id: 7, title: 'Pembayaran via BNI Internet Banking', content: '<ol><li>Login ke internet banking BNI.</li><li>Klik <strong>Transfer</strong> > <strong>Virtual Account Billing</strong>.</li><li>Masukkan nomor Virtual Account.</li><li>Pilih rekening sumber dana.</li><li>Jumlah pembayaran akan ditampilkan di layar.</li><li>Masukkan kode token autentikasi.</li></ol>', sort_order: 2 },
    { id: 10, payment_method_id: 7, title: 'Pembayaran via ATM BNI', content: '<ol><li>Masukkan Kartu ATM.</li><li>Pilih bahasa yang diinginkan.</li><li>Masukkan PIN ATM.</li><li>Pilih <strong>Menu Lain</strong> > <strong>Transfer</strong>.</li><li>Pilih jenis rekening sumber dana.</li><li>Pilih <strong>Virtual Account Billing</strong> dan masukkan nomor Virtual Account.</li><li>Jumlah pembayaran akan ditampilkan di layar.</li><li>Konfirmasi informasi pembayaran.</li></ol>', sort_order: 3 },

    { id: 11, payment_method_id: 8, title: 'Pembayaran via BJB Mobile', content: '<ol><li>Buka aplikasi BJB Mobile.</li><li>Masukkan User ID dan Password.</li><li>Pilih <strong>Virtual Account</strong>.</li><li>Pilih jenis rekening sumber dana (misal: Tabungan).</li><li>Masukkan Nomor Virtual Account.</li><li>Konfirmasi detail transaksi Anda.</li></ol>', sort_order: 1 },
    { id: 12, payment_method_id: 8, title: 'Pembayaran via BJB Net', content: '<ol><li>Buka BJB Net.</li><li>Masukkan User ID dan Password.</li><li>Pilih <strong>Virtual Account</strong>.</li><li>Pilih jenis rekening sumber dana.</li><li>Masukkan Nomor Virtual Account.</li><li>Konfirmasi detail transaksi Anda.</li></ol>', sort_order: 2 },
    { id: 13, payment_method_id: 8, title: 'Pembayaran via ATM BJB', content: '<ol><li>Masukkan kartu ATM BJB dan PIN Anda.</li><li>Pilih Menu <strong>Transaksi Lainnya</strong>.</li><li>Pilih <strong>Virtual Account</strong>.</li><li>Pilih jenis rekening sumber dana.</li><li>Masukkan Nomor Virtual Account.</li><li>Konfirmasi detail transaksi Anda.</li></ol>', sort_order: 3 },

    { id: 14, payment_method_id: 9, title: 'Pembayaran via BNC Mobile / Neobank', content: '<ol><li>Login ke aplikasi BNC Mobile atau Neobank.</li><li>Klik <strong>Hematpay VA & QRIS</strong>.</li><li>Masukkan nomor Virtual Account.</li><li>Masukkan jumlah pembayaran.</li><li>Konfirmasi informasi pembayaran.</li><li>Masukkan PIN.</li></ol>', sort_order: 1 },
    { id: 15, payment_method_id: 9, title: 'Pembayaran via ATM BNC', content: '<ol><li>Masukkan Kartu ATM.</li><li>Pilih bahasa yang diinginkan.</li><li>Masukkan PIN ATM.</li><li>Pilih <strong>Pembayaran VA</strong>.</li><li>Masukkan nomor Virtual Account.</li><li>Masukkan jumlah pembayaran.</li><li>Konfirmasi informasi pembayaran.</li><li>Masukkan PIN.</li></ol>', sort_order: 2 },

    { id: 16, payment_method_id: 4, title: 'Pembayaran via BYOND BSI', content: '<ol><li>Login ke BYOND BSI.</li><li>Pilih <strong>Bayar & Beli</strong>.</li><li>Cari Xendit, Pilih Prefix VA: 9347 atau 9655.</li><li>Masukkan kode VA (tanpa prefix).</li><li>Masukkan PIN.</li><li>Konfirmasi detail pembayaran.</li></ol>', sort_order: 1 },
    { id: 17, payment_method_id: 4, title: 'Pembayaran via BSI Internet Banking', content: '<ol><li>Login ke BSI Net.</li><li>Klik <strong>Pembayaran</strong>.</li><li>Pilih sumber dana.</li><li>Klik <strong>Institusi</strong>.</li><li>Masukkan Xendit sebagai nama institusi (kode 9347).</li><li>Masukkan nomor Virtual Account.</li><li>Konfirmasi detail pembayaran.</li><li>Masukkan kode token autentikasi.</li></ol>', sort_order: 2 },
    { id: 18, payment_method_id: 4, title: 'Pembayaran via ATM BSI', content: '<ol><li>Masukkan Kartu ATM BSI.</li><li>Pilih bahasa yang diinginkan.</li><li>Masukkan PIN ATM.</li><li>Pilih <strong>Pembayaran/Pembelian</strong> > <strong>Institusi</strong>.</li><li>Masukkan nomor Virtual Account.</li><li>Konfirmasi detail pembayaran.</li></ol>', sort_order: 3 },

    { id: 19, payment_method_id: 10, title: 'Pembayaran via OCTO Mobile', content: '<ol><li>Buka OCTO Mobile dan masukkan User ID dan Password.</li><li>Pilih menu <strong>Transfer</strong> lalu pilih <strong>CIMB Niaga Lainnya</strong>.</li><li>Masukkan Nomor Virtual Account pada menu Input Baru.</li><li>Masukkan jumlah pembayaran.</li><li>Konfirmasi transaksi dan masukkan password/PIN Anda.</li></ol>', sort_order: 1 },
    { id: 20, payment_method_id: 10, title: 'Pembayaran via ATM CIMB Niaga', content: '<ol><li>Masukkan Kartu ATM Anda.</li><li>Pilih bahasa yang diinginkan.</li><li>Masukkan PIN ATM.</li><li>Pilih menu <strong>Transfer</strong> lalu pilih <strong>CIMB Niaga Lainnya</strong>.</li><li>Masukkan Nomor Virtual Account.</li><li>Masukkan jumlah pembayaran.</li><li>Konfirmasi transaksi Anda.</li></ol>', sort_order: 2 },
    { id: 21, payment_method_id: 10, title: 'Pembayaran via OCTO Clicks', content: '<ol><li>Login ke OCTO Clicks.</li><li>Pilih menu <strong>Transfer</strong> lalu pilih <strong>CIMB Niaga Lainnya</strong>.</li><li>Masukkan Nomor Virtual Account pada menu Input Baru.</li><li>Masukkan jumlah pembayaran.</li><li>Konfirmasi transaksi dan masukkan password Anda.</li></ol>', sort_order: 3 },

    { id: 22, payment_method_id: 11, title: 'Pembayaran via MDIN (Mobile Muamalat)', content: '<ol><li>Login ke aplikasi MDIN.</li><li>Pilih <strong>Beli/Bayar</strong> > <strong>Beli/Bayar Tagihan</strong> > <strong>Virtual Account</strong>.</li><li>Masukkan nomor Virtual Account.</li><li>Masukkan jumlah pembayaran.</li><li>Konfirmasi detail pembayaran.</li><li>Masukkan PIN.</li></ol>', sort_order: 1 },
    { id: 23, payment_method_id: 11, title: 'Pembayaran via Muamalat Internet Banking', content: '<ol><li>Login ke Muamalat Internet Banking.</li><li>Klik <strong>Pembayaran</strong> > <strong>Virtual Account</strong>.</li><li>Masukkan nomor Virtual Account.</li><li>Masukkan jumlah pembayaran.</li><li>Konfirmasi detail pembayaran.</li><li>Masukkan PIN.</li></ol>', sort_order: 2 },
    { id: 24, payment_method_id: 11, title: 'Pembayaran via ATM Muamalat', content: '<ol><li>Masukkan Kartu ATM.</li><li>Pilih bahasa yang diinginkan.</li><li>Masukkan PIN ATM.</li><li>Pilih <strong>Pembayaran</strong> > <strong>Virtual Account</strong>.</li><li>Masukkan nomor Virtual Account.</li><li>Masukkan jumlah pembayaran.</li><li>Konfirmasi detail pembayaran.</li><li>Masukkan PIN.</li></ol>', sort_order: 3 },

    { id: 25, payment_method_id: 12, title: 'Pembayaran via Permata Mobile App', content: '<ol><li>Login ke aplikasi PermataMobile X.</li><li>Pilih <strong>Pembayaran Tagihan</strong> > <strong>Virtual Account</strong>.</li><li>Masukkan nomor Virtual Account.</li><li>Masukkan token autentikasi.</li></ol>', sort_order: 1 },
    { id: 26, payment_method_id: 12, title: 'Pembayaran via PermataNet', content: '<ol><li>Login ke PermataNet.</li><li>Pilih <strong>Pembayaran Tagihan</strong> > <strong>Virtual Account</strong>.</li><li>Masukkan nomor Virtual Account.</li><li>Konfirmasi detail pembayaran.</li><li>Masukkan kode respon token SMS.</li></ol>', sort_order: 2 },
    { id: 27, payment_method_id: 12, title: 'Pembayaran via ATM Permata', content: '<ol><li>Masukkan Kartu ATM.</li><li>Pilih bahasa yang diinginkan.</li><li>Masukkan PIN ATM.</li><li>Pilih <strong>Transaksi Lainnya</strong> > <strong>Pembayaran</strong> > <strong>Pembayaran Lainnya</strong> > <strong>Virtual Account</strong>.</li><li>Masukkan nomor Virtual Account.</li><li>Konfirmasi detail pembayaran.</li><li>Masukkan PIN.</li></ol>', sort_order: 3 },

    { id: 28, payment_method_id: 13, title: 'Pembayaran via Alfamart', content: '<ol><li>Kunjungi cabang ALFAMART, Alfamidi, Dan+Dan, atau Lawson terdekat sebelum waktu kedaluwarsa habis.</li><li>Beri tahu kasir bahwa Anda ingin melakukan pembayaran "Yayasan Peduli Sesama" via Xendit atau tunjukkan barcode pembayaran.</li><li>Tunjukkan kode pembayaran/barcode ke kasir dan konfirmasikan jumlahnya.</li><li>Lakukan pembayaran sesuai dengan nominal tagihan.</li></ol>', sort_order: 1 },

    { id: 29, payment_method_id: 14, title: 'Pembayaran via Indomaret', content: '<ol><li>Kunjungi cabang INDOMARET terdekat sebelum waktu kedaluwarsa habis.</li><li>Beri tahu kasir untuk melakukan pembayaran Xendit.</li><li>Sebutkan kode pembayaran ke Kasir atau tunjukkan barcode.</li><li>Konfirmasikan jumlah tagihan kepada kasir lalu lakukan pembayaran.</li></ol>', sort_order: 1 },

    { id: 30, payment_method_id: 1, title: 'Pembayaran dengan Aplikasi Gojek / GoPay', content: '<ol><li>Buka aplikasi Gojek atau dompet digital Anda.</li><li>Pilih menu <strong>Bayar / Scan</strong>.</li><li>Scan QR Code yang tampil di layar atau upload dari galeri.</li></ol>', sort_order: 1 },
    { id: 31, payment_method_id: 5, title: 'Transfer via ATM / M-Banking BSI', content: '<ol><li>Login ke aplikasi BSI Mobile atau datangi ATM BSI terdekat.</li><li>Pilih menu <strong>Transfer</strong> > <strong>Antar Rekening BSI</strong>.</li><li>Masukkan rekening tujuan: <strong>7123456789</strong>.</li><li>Pastikan nama penerima: <strong>Yayasan Peduli Sesama</strong>.</li><li>Transfer dana sesuai dengan nominal tagihan hingga 3 digit terakhir.</li><li>Simpan bukti transfer dan unggah pada halaman status.</li></ol>', sort_order: 1 },
  ]
};

let pmSql = 'INSERT INTO "public"."payment_methods" ("id", "code", "name", "logo_url", "type", "provider", "admin_fee_flat", "admin_fee_pct", "is_active", "is_redirect", "sort_order") VALUES\n';
pmSql += data.payment_methods.map(pm => `(${pm.id}, '${pm.code}', '${pm.name}', '${pm.logo_url || ''}', '${pm.type}', '${pm.provider}', ${pm.code.includes('VA') ? 4000 : (['ALFAMART','INDOMARET'].includes(pm.code) ? 5000 : 0)}, 0.00, '${pm.is_active ? 't' : 'f'}', 'f', ${pm.sort_order})`).join(',\n') + ';';

let piSql = 'INSERT INTO "public"."payment_instructions" ("id", "payment_method_id", "title", "content", "sort_order", "created_at") VALUES\n';
piSql += data.payment_instructions.map(pi => `(${pi.id}, ${pi.payment_method_id}, '${pi.title}', '${pi.content}', ${pi.sort_order}, '2026-04-19 01:39:51.048594+00')`).join(',\n') + ';';

fs.writeFileSync('scratch/seed.sql', pmSql + '\n\n' + piSql);
console.log('Done');
